---

# ansible build using jenkins and uplink/downlink builds

- hosts: slave
  remote_user: jenkins
  sudo: yes

  tasks:

    - name: install nginx & pip
      yum: name={{ item }} state=absent
      with_items:
         - nginx
         - python-pip

- hosts: localhost
  tasks:

     - name: install pip
       yum: name={{ item }} state=present
       with_items:
          - python-pip
          - facter

     - name: install ansible-lint
       pip: name=ansible-lint

- hosts: all
  tasks:
- include: test.yml
